language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install pep8 pyflakes pylint --use-mirrors
  - pip install pycairo --use-mirrors
  - pip install coveralls --use-mirrors
script: make test maps
after_success:
  - coveralls
