language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install pep8 pyflakes pylint --use-mirrors
  - pip install coverage coveralls --use-mirrors
script: make test coverage
after_success:
  - coveralls
notifications:
  email: false
